server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.198.132:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      pool-name: SPHHikariPool
      minimum-idle: 10
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: 192.168.198.132
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  default-flat-param-object: true # 把json格式展开

aliyun:
  sms:
    access-key-id: LTAI5tLPtZbvQKtJxpjSepat
    access-key-secret: qKo8WOrS6JUqeGJhcBDCfMl0iWcidZ
    endpoint: dysmsapi.aliyuns.com